server:
  port: 8089
spring:
  application:
    name: demo-zuul

zuul:
  routes:
    api-user:
      path: /demo-user/**
      serviceId: demo-user
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
